/**
 * monaco-setup.js
 *
 * Configures Monaco Editor's Web Worker environment BEFORE Monaco loads.
 *
 * WHY THIS FILE EXISTS
 * Monaco offloads heavy language work (parsing, diagnostics, IntelliSense)
 * to Web Workers so the main thread stays responsive. It needs to know
 * the URL of each worker script at startup.
 *
 * WHY IT MUST BE THE FIRST IMPORT
 * ES module imports are hoisted — they all execute before any module code runs,
 * in depth-first order. By importing this file first in index.js, its code
 * runs before monaco-editor initialises and reads MonacoEnvironment.
 *
 * WORKER FILES (generated by MonacoWebpackPlugin in webpack.config.cjs):
 *   /editor.worker.js  — base worker for all languages (cursor, layout, etc.)
 *   /ts.worker.js      — TypeScript/JavaScript language services
 *                        (syntax highlighting, diagnostics, completions)
 */

self.MonacoEnvironment = {
    /**
     * Called by Monaco once per worker type to get the worker script URL.
     * @param {string} _moduleId - internal module ID (unused)
     * @param {string} label     - language identifier e.g. "javascript", "css"
     * @returns {string} absolute path to the worker script
     */
    getWorkerUrl(_moduleId, label) {
        // JavaScript uses the TypeScript worker because Monaco's JS support
        // is built on top of its TypeScript language service.
        if (label === "typescript" || label === "javascript") {
            return "/ts.worker.js";
        }
        // All other languages fall back to the lightweight base editor worker.
        return "/editor.worker.js";
    },
};
